name: Deploy to Development

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '22'
  AWS_REGION: eu-west-3
  S3_BUCKET_DEV: maturity-frontend-dev-637423285771
  ENVIRONMENT: dev

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    environment: development
    
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
    
    - name: Build frontend
      run: npm run build
      env:
        NODE_ENV: production
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Deploy to S3
      run: |
        aws s3 sync ./dist s3://${{ env.S3_BUCKET_DEV }} \
          --delete \
          --exclude "*.map" \
          --cache-control "public,max-age=31536000,immutable" \
          --exclude "index.html" \
          --exclude "service-worker.js"
        
        # Upload index.html with no-cache
        aws s3 cp ./dist/index.html s3://${{ env.S3_BUCKET_DEV }}/index.html \
          --cache-control "public,max-age=0,must-revalidate"
    
    - name: Invalidate CloudFront
      run: |
        DISTRIBUTION_ID=$(aws cloudfront list-distributions \
          --query "DistributionList.Items[?contains(Origins.Items[0].DomainName, '${{ env.S3_BUCKET_DEV }}')].Id" \
          --output text)
        
        if [ -n "$DISTRIBUTION_ID" ]; then
          aws cloudfront create-invalidation \
            --distribution-id $DISTRIBUTION_ID \
            --paths "/*"
          echo "✅ CloudFront invalidation created for: $DISTRIBUTION_ID"
        else
          echo "❌ CloudFront distribution not found"
          exit 1
        fi
    
    - name: Deployment summary
      run: |
        echo "🚀 Deployment to DEV completed successfully!"
        echo "📱 Frontend URL: https://dev-maturity.e-dsin.fr"
        echo "🔗 CloudFront URL: Available in AWS Console"
        echo "📦 S3 Bucket: ${{ env.S3_BUCKET_DEV }}"